<?php
use Application\Model\TranslationBase;
use Application\Model\Translation;
/**
 * @var Zend\View\Renderer\PhpRenderer $this
 *
 * @var array $supportedLocales of strings
 * @var string $currentLocale
 * @var array $messages of strings
 * @var TranslationBase $baseTranslation
 * @var array $translations of Translation with index locale
 */
//var_dump($translations);
?>
<ul class="messages row">
    <?php if (isset($messages)): ?>
        <?php foreach ($messages as $messageLevel => $messageLevelContainer): ?>
            <?php foreach ($messageLevelContainer as $message): ?>
                <li class="alert alert-<?php echo $this->escapeHtmlAttr($messageLevel); ?>" role="alert">
                    <?php echo $this->escapeHtml($message); ?>
                </li>
            <?php endforeach; ?>
        <?php endforeach; ?>
    <?php endif; ?>
</ul>

<div class="panel panel-default">
    <div class="panel-heading"><b>Basic data</b></div>
    <div class="panel-body">

        <div class="btn-group">
            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                Language <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" role="menu">
                <?php foreach ($supportedLocales as $locale): ?>
                    <li><a href="<?php echo $this->url('home', array('action' => 'edit', 'base_id' => $baseTranslation->getBaseId()), array('query' => array('locale' => $locale))); ?>">
                            <?php echo $locale ?></a>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
        <b>selected file:</b> <span class="label label-primary"><?php echo $this->escapeHtml($baseTranslation->getTranslationFile()) ?></span> <b>selected language:</b> <span class="label label-default"><?php echo $currentLocale ?></span>
    </div>
</div>

<div class="row">
    <div class="col-md-4">
        <form action="" method="post">
            <input type="hidden" name="translation_locale" value="<?php echo $this->escapeHtmlAttr($currentLocale) ?>" />
            <input type="hidden" name="base_id" value="<?php echo $baseTranslation->getBaseId() ?>" />
            <input type="hidden" name="translation_id" value="<?php echo $translations[$currentLocale]->getId() ?>" />

            <div class="panel panel-default">
                <div class="panel-heading">
                    <strong>Origin source</strong><br/>
                    <?php if ((bool)$baseTranslation->getNotInUse()): ?>
                    <span class="label label-danger">Not in use anymore</span>
                    <?php endif; ?>
                </div>
                <div class="panel-body">
                    <?php echo $this->escapeHtml($baseTranslation->getOriginSource()); ?>
                </div>
            </div>

            <div class="panel panel-default">
                <div class="panel-heading"><strong>Current translation</strong> (<?php echo $currentLocale ?>)</div>
                <div class="panel-body">
                    <?php echo $this->escapeHtml($translations[$currentLocale]->getCurrentTranslation()); ?>
                </div>
            </div>

            <div class="panel panel-default">
                <div class="panel-heading"><strong>Unclear translation</strong></div>
                <div class="panel-body">
                    <?php $unclearSelected = (bool)$translations[$currentLocale]->getUnclearTranslation() ?>
                    <input type="checkbox" name="unclear_translation" value="1" <?php if ($unclearSelected) echo 'selected="selected"' ?>/> is unclear translation
                </div>
            </div>

            <div class="panel panel-default">
                <div class="panel-heading"><strong>New suggested translation</strong> (<?php echo $currentLocale ?>)</div>
                <div class="panel-body">
                    <div class="input-group">
                        <textarea class="form-control" rows="3" name="suggested_translation"><?php echo $this->escapeHtml($translations[$currentLocale]->getSuggestedTranslation()) ?></textarea>
                        <button type="submit" value="row<?php echo $translations[$currentLocale]->getId() ?>" name="rowid" class="btn btn-primary" style="margin-top: 15px;">Save entry</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
    <div class="col-md-8">

        <div class="panel panel-default">
            <div class="panel-heading">Usage</div>
            <div class="panel-body">
                <?php if ('' != $baseTranslation->getScreenPath()): ?>
                    <a href="<?php echo $this->basePath('usages/' . $baseTranslation->getScreenPath()) ?>" target="_blank">
                    <img class="img-responsive" src="<?php echo $this->basePath('usages/' . $baseTranslation->getScreenPath()) ?>" />
                    </a>
                <?php else: ?>
                    <p>No image for usage available.</p>
                <?php endif; ?>
            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-heading">Navigation</div>
            <div class="panel-body">
                <div class="btn-group">
                    <!--a class="btn btn-default" href="">Previous translation</a-->
                    <a class="btn btn-default" href="<?php echo $this->url('home', array('action' => 'index'), array('query' => array('locale' => $currentLocale))) ?>">Back to overall view list</a>
                    <!--a class="btn btn-default" href="">Next translation</a-->
                </div>

            </div>
        </div>

    </div>
</div>