<?php
use Application\Model\TranslationBase;
use Application\Model\Translation;

/**
 * @var $this Zend\View\Renderer\PhpRenderer
 *
 * @var string[] $supportedLocales
 * @var Translation[] $translations with index translation_id
 * @var TranslationBase[] $translationBase with index translation_base_id
 * @var string[] $translationFiles
 * @var int $translationsCount
 * @var string $currentLocale
 * @var string[] $currentFile
 * @var boolean $currentFilterUnclear
 * @var int $currentPage
 * @var int $currentEPP - entries per page
 * @var int $maxPages
 * @var string[] messages with index messageLevel
 * @var string $jumpToRow
 */
?>
<div>
    <p><?php //echo sprintf($this->translate('Congratulations! You have successfully installed the %sZF2 Skeleton Application%s. You are currently running Zend Framework version %s. This skeleton can serve as a simple starting point for you to begin building your application on ZF2.'), '<a href="https://github.com/zendframework/ZendSkeletonApplication" target="_blank">', '</a>', \Zend\Version\Version::VERSION) ?></p>
</div>
<ul class="messages row">
    <?php if (isset($messages)): ?>
        <?php foreach ($messages as $messageLevel => $messageLevelContainer): ?>
            <?php foreach ($messageLevelContainer as $message): ?>
                <li class="alert alert-<?php echo $this->escapeHtmlAttr($messageLevel); ?>" role="alert">
                    <?php echo $this->escapeHtml($message); ?>
                </li>
            <?php endforeach; ?>
        <?php endforeach; ?>
    <?php endif; ?>
</ul>

<div class="row">
    <div class="panel panel-default filter-area">
        <div class="panel-heading"><strong><?php echo $this->translate('Filter') ?></strong></div>
        <div class="panel-body">

            <div class="btn-group">
                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                    <?php echo $this->translate('Translation file') ?> <span class="caret"></span>
                </button>
                <ul class="dropdown-menu" role="menu">
                    <li><a href="<?php echo $this->url('home', array(), array('query' => array('locale' => $currentLocale, 'file' => null, 'filter_unclear_translation' => $currentFilterUnclear))); ?>"><?php echo $this->translate('all files') ?></a></li>
                    <?php foreach ($translationFiles as $fileName): ?>
                    <li><a href="<?php echo $this->url('home', array(), array('query' => array('locale' => $currentLocale, 'file' => $fileName, 'filter_unclear_translation' => $currentFilterUnclear))); ?>">
                            <?php echo $fileName ?></a>
                    </li>
                    <?php endforeach; ?>
                </ul>
            </div>

            <div class="btn-group">
                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                    <?php echo $this->translate('Language') ?> <span class="caret"></span>
                </button>
                <ul class="dropdown-menu" role="menu">
                    <?php foreach ($supportedLocales as $locale): ?>
                        <li><a href="<?php echo $this->url('home', array(), array('query' => array('locale' => $locale, 'file' => $currentFile, 'filter_unclear_translation' => $currentFilterUnclear))); ?>">
                                <?php echo $locale ?></a>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </div>
            <strong><?php echo $this->translate('selected file:') ?></strong>
            <?php if (empty($currentFile)): ?>
                <span class="label label-info"><?php echo $this->translate('all files') ?></span>
            <?php else: ?>
                <?php foreach ($currentFile as $fileName): ?>
                    <span class="label label-primary"><?php echo $fileName ?></span>
                <?php endforeach; ?>
            <?php endif; ?>

            <strong><?php echo $this->translate('selected language:') ?></strong> <span class="label label-default"><?php echo $currentLocale ?></span>
            <strong><?php echo $this->translate('unclear translations:') ?> </strong>
            <?php if ($currentFilterUnclear): ?>
                <button class="btn btn-primary" onclick="location.href='<?php echo $this->url('home', array(), array('query' => array('locale' => $currentLocale, 'file' => $currentFile, 'filter_unclear_translation' => 0))) ?>'">
                    <?php echo $this->translate('show only unclear') ?>
                </button>
            <?php else: ?>
                <button class="btn btn-default" onclick="location.href='<?php echo $this->url('home', array(), array('query' => array('locale' => $currentLocale, 'file' => $currentFile, 'filter_unclear_translation' => 1))) ?>'">
                    <?php echo $this->translate('show only unclear') ?>
                </button>
            <?php endif; ?>

            <br />

            <ul class="pagination">
                <?php if ($currentPage > 1): ?>
                    <li><a href="<?php echo $this->url('home', array(), array('query' => array('locale' => $currentLocale, 'file' => $currentFile, 'filter_unclear_translation' => $currentFilterUnclear, 'page' => $currentPage - 1, 'epp' => $currentEPP))); ?>" aria-label="Previous">
                        &laquo;
                    </a></li>
                <?php endif; ?>
                <?php for ($i = 1; $i <= $maxPages; $i++): ?>
                    <?php $class = ($i == $currentPage) ? 'active' : ''; ?>
                    <li class="<?php echo $class ?>"><a href="<?php echo $this->url('home', array(), array('query' => array('locale' => $currentLocale, 'file' => $currentFile, 'filter_unclear_translation' => $currentFilterUnclear, 'page' => $i, 'epp' => $currentEPP))); ?>">
                        <?php echo $i ?>
                    </a></li>
                <?php endfor; ?>
                <?php if ($currentPage < $maxPages): ?>
                    <li><a href="<?php echo $this->url('home', array(), array('query' => array('locale' => $currentLocale, 'file' => $currentFile, 'filter_unclear_translation' => $currentFilterUnclear, 'page' => $currentPage + 1, 'epp' => $currentEPP))); ?>" aria-label="Next">
                        &raquo;
                    </a></li>
                <?php endif; ?>
            </ul>

            <span id="entries-per-page-button" style="margin-left: 10px"><!-- TODO: where comes the top margin from (see CSS)? -->
                <div class="btn-group">
                    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                        <?php echo $this->translate('Entries per page') ?> <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu" role="menu">
                        <li><a href="<?php echo $this->url('home', array(), array('query' => array('locale' => $currentLocale, 'file' => $currentFile, 'filter_unclear_translation' => $currentFilterUnclear, 'page' => $currentPage, 'epp' => 25))); ?>">
                            25
                        </a></li>
                        <li><a href="<?php echo $this->url('home', array(), array('query' => array('locale' => $currentLocale, 'file' => $currentFile, 'filter_unclear_translation' => $currentFilterUnclear, 'page' => $currentPage, 'epp' => 50))); ?>">
                            50
                        </a></li>
                        <li><a href="<?php echo $this->url('home', array(), array('query' => array('locale' => $currentLocale, 'file' => $currentFile, 'filter_unclear_translation' => $currentFilterUnclear, 'page' => $currentPage, 'epp' => 100))); ?>">
                            100
                        </a></li>
                        <li><a href="<?php echo $this->url('home', array(), array('query' => array('locale' => $currentLocale, 'file' => $currentFile, 'filter_unclear_translation' => $currentFilterUnclear, 'page' => $currentPage, 'epp' => 250))); ?>">
                            250
                        </a></li>
                        <li><a href="<?php echo $this->url('home', array(), array('query' => array('locale' => $currentLocale, 'file' => $currentFile, 'filter_unclear_translation' => $currentFilterUnclear, 'page' => $currentPage, 'epp' => 'all'))); ?>">
                            <?php echo $this->translate('all' ) ?>
                        </a></li>
                    </ul>
                </div>
                <strong><?php echo $this->translate('per page:') ?> </strong><span class="label label-default"><?php echo (null !== $currentEPP) ? (int)$currentEPP : $this->translate('all') ?></span>
            </span>
        </div>
    </div>

    <div class="panel panel-default">
        <div class="panel-heading"><strong><?php echo $this->translate('overall view list') ?></strong> (<?php echo count($translations) ?> / <?php echo (int)$translationsCount ?> <?php echo $this->translate('elements') ?>)</div>
        <div class="panel-body">
            <form action="" method="post">
                <input type="hidden" name="translation_locale" value="<?php echo $this->escapeHtmlAttr($currentLocale) ?>" />
                <table class="table table-hover" id="translation-grid">
                    <tr>
                        <th><?php echo $this->translate('Origin source') ?></th>
                        <th><?php echo $this->translate('Current translation') ?></th>
                        <th><span title="<?php echo $this->translate('unclear translation') ?>"><?php echo $this->translate('Status') ?></span></th>
                        <th><?php echo $this->translate('New suggested translation') ?></th>
                        <th></th>
                    </tr>
                    <?php foreach ($translations as $id => $translation): ?>
                        <?php /* @var $base TranslationBase */ ?>
                        <?php $base = $translationBase[$translation['base_id']] ?>
                        <?php $rowName = 'row' . $translation['base_id']; ?>
                        <tr id="<?php echo $rowName ?>">
                            <td><?php echo $this->escapeHtml($base ->getOriginSource()) ?></td>
                            <td><?php echo $this->escapeHtml($translation['current_translation']) ?></td>
                            <td class="text-center">
                                <?php if ((bool)$translation['unclear_translation']): ?>
                                    <button class="unclear-translation" title="<?php echo $this->translate('unclear translation at the moment') ?>" type="button"
                                            onclick="toggleUnclearTranslation($(this))" data-translation-id="<?php echo $this->escapeHtmlAttr($translation['translation_id'])?>">
                                        <i class="glyphicon glyphicon-exclamation-sign unclear"></i>
                                    </button>
                                <?php else: ?>
                                    <button class="unclear-translation" title="<?php echo $this->translate('clear translation at the moment') ?>" type="button"
                                            onclick="toggleUnclearTranslation($(this))" data-translation-id="<?php echo $this->escapeHtmlAttr($translation['translation_id'])?>">
                                        <i class="glyphicon glyphicon-ok-circle clear"></i>
                                    </button>
                                <?php endif; ?>
                            </td>
                            <td class="suggested-translation">
                                <input type="text" class="form-control" name="<?php echo $rowName?>_suggestedTranslation" value="" />
                            </td>
                            <td>
                                <div style="min-width: 125px">
                                    <input type="hidden" name="<?php echo $rowName?>_baseId" value="<?php echo $this->escapeHtmlAttr($translation['base_id'])?>" />
                                    <input type="hidden" name="<?php echo $rowName?>_translationId" value="<?php echo $this->escapeHtmlAttr($translation['translation_id'])?>" />
                                    <button type="submit" value="<?php echo $rowName?>" name="rowid" class="btn btn-primary btn-lg" data-toggle="tooltip" data-placement="right" title="<?php echo $this->translate('Add suggestion') ?>"><span class="glyphicon glyphicon-plus"></span></button>
                                    &nbsp;
                                    <a class="btn btn-default btn-lg" data-toggle="tooltip" data-placement="right" title="<?php echo $this->translate('See Details') ?>" href="<?php echo $this->url('index', array('action' => 'edit', 'base_id' => $translation['base_id']), array('query' => array('locale' => $currentLocale))) ?>"><span class="glyphicon glyphicon-search"></span></a>
                                </div>
                            </td>
                        </tr>
                    <?php endforeach; ?>

                </table>
                <button type="submit" value="all" name="rowid" class="btn btn-primary"><?php echo $this->translate('Submit all') ?></button>
            </form>
        </div>
    </div>

</div>
<script>
    <?php if ($jumpToRow): ?>
        $(document).ready(function () {
            // if some suggestion is saved, jump to the row in the grid to be in focus to the next data set
            $('html, body').animate({
                scrollTop: $("#<?php echo $jumpToRow ?>").offset().top - $("#navbar").outerHeight()
            }, 1000);
        });
    <?php endif; ?>

    // toggle unclear translation flag
    function toggleUnclearTranslation(toggleButton) {
        var translationId = toggleButton.data("translation-id");
        $.ajax({
            type: "POST",
            url: "<?php echo $this->url('ajax', array('action' => 'toggle_unclear')); ?>",
            data: {"translation_id": translationId},
            success: function(data) {
                if (false == data.success) {
                    alert("An error occurred toggling the unclear status of element " + translationId + ":\n" + data.error)
                    return;
                }

                // change status in frontend
                if (false == data.new_state) {
                    toggleButton.attr("title", "clear translation at the moment");
                    toggleButton.html("<i class=\"glyphicon glyphicon-ok-circle clear\"></i>");
                } else {
                    toggleButton.attr("title", "unclear translation at the moment");
                    toggleButton.html("<i class=\"glyphicon glyphicon-exclamation-sign unclear\"></i>");
                }
            },
            error: function() {
                alert("An error occurred toggling the unclear translation status");
            }
        });
    }
</script>
