<?php
/**
 * @var $this Zend\View\Renderer\PhpRenderer
 *
 * @var array $supportedLocales of string
 * @var array $translations of Translation
 * @var array $translationBase of TranslationBase
 * @var array $translationFiles of string
 * @var string $currentLocale
 * @var array $currentFile of string
 * @var boolean $currentFilterUnclear
 */
?>
<div>
    <p><?php //echo sprintf($this->translate('Congratulations! You have successfully installed the %sZF2 Skeleton Application%s. You are currently running Zend Framework version %s. This skeleton can serve as a simple starting point for you to begin building your application on ZF2.'), '<a href="https://github.com/zendframework/ZendSkeletonApplication" target="_blank">', '</a>', \Zend\Version\Version::VERSION) ?></p>
</div>
<ul class="messages row">
    <?php if (isset($messages)): ?>
        <?php foreach ($messages as $messageLevel => $messageLevelContainer): ?>
            <?php foreach ($messageLevelContainer as $message): ?>
                <li class="alert alert-<?php echo $this->escapeHtmlAttr($messageLevel); ?>" role="alert">
                    <?php echo $this->escapeHtml($message); ?>
                </li>
            <?php endforeach; ?>
        <?php endforeach; ?>
    <?php endif; ?>
</ul>

<div class="row">
    <div class="panel panel-default">
        <div class="panel-heading"><b>Basic data</b></div>
        <div class="panel-body">

            <div class="btn-group">
                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                    Translation file <span class="caret"></span>
                </button>
                <ul class="dropdown-menu" role="menu">
                    <li><a href="<?php echo $this->url('home', array(), array('query' => array('locale' => $currentLocale, 'file' => null))); ?>">all files</a></li>
                    <?php foreach ($translationFiles as $fileName): ?>
                    <li><a href="<?php echo $this->url('home', array(), array('query' => array('locale' => $currentLocale, 'file' => $fileName))); ?>">
                            <?php echo $fileName ?></a>
                    </li>
                    <?php endforeach; ?>
                </ul>
            </div>

            <div class="btn-group">
                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                    Language <span class="caret"></span>
                </button>
                <ul class="dropdown-menu" role="menu">
                    <?php foreach ($supportedLocales as $locale): ?>
                        <li><a href="<?php echo $this->url('home', array(), array('query' => array('locale' => $locale, 'file' => $currentFile))); ?>">
                                <?php echo $locale ?></a>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </div>
            <strong>selected file:</strong>
            <?php if (empty($currentFile)): ?>
                <span class="label label-info">all files</span>
            <?php else: ?>
                <?php foreach ($currentFile as $fileName): ?>
                    <span class="label label-primary"><?php echo $fileName ?></span>
                <?php endforeach; ?>
            <?php endif; ?>

            <strong>selected language:</strong> <span class="label label-default"><?php echo $currentLocale ?></span>
            <strong>unclear translations: </strong>
            <?php if ($currentFilterUnclear): ?>
                <button class="btn btn-primary" onclick="location.href='<?php echo $this->url('home', array(), array('query' => array('locale' => $currentLocale, 'file' => $currentFile, 'filter_unclear_translation' => 0))) ?>'">
                    show only unclear
                </button>
            <?php else: ?>
                <button class="btn btn-default" onclick="location.href='<?php echo $this->url('home', array(), array('query' => array('locale' => $currentLocale, 'file' => $currentFile, 'filter_unclear_translation' => 1))) ?>'">
                    show only unclear
                </button>
            <?php endif; ?>
        </div>
    </div>

    <div class="panel panel-default">
        <div class="panel-heading"><b>overall view list</b></div>
        <div class="panel-body">
            <form action="" method="post">
                <input type="hidden" name="translation_locale" value="<?php echo $this->escapeHtmlAttr($currentLocale) ?>" />
                <table class="table table-hover" id="translation-grid">
                    <tr>
                        <th>Origin source<th>
                        <th>Current translation<th>
                        <th><span class="glyphicon glyphicon-cloud" title="unclear translation"></span></th>
                        <th>New suggested translation<th>
                        <th><th>
                    </tr>
                    <?php $rowNumber = 0; ?>
                    <?php foreach ($translations as $id => $translation): $rowNumber++; ?>
                        <?php /* @var $translation \Application\Model\Translation */ ?>
                        <?php /* @var $base \Application\Model\TranslationBase */ ?>
                        <?php $base = $translationBase[$translation['base_id']] ?>
                        <?php $rowName = 'row' . $rowNumber; ?>
                        <tr>
                            <td><?php echo $this->escapeHtml($base ->getOriginSource()) ?><td>
                            <td><?php echo $this->escapeHtml($translation['current_translation']) ?><td>
                            <td>
                                <input type="checkbox" name="<?php echo $rowName?>_unclearTranslation" value="1" <?php echo (bool)($translation['unclear_translation']) ? 'checked="checked"':'' ?>>
                            </td>
                            <td class="suggested-translation">
                                <input type="text" class="form-control" name="<?php echo $rowName?>_suggestedTranslation" value="<?php echo $this->escapeHtmlAttr($translation['suggested_translation']) ?>" />
                            <td>
                            <td>
                                <div style="min-width: 125px">
                                    <input type="hidden" name="<?php echo $rowName?>_baseId" value="<?php echo $this->escapeHtmlAttr($translation['base_id'])?>" />
                                    <input type="hidden" name="<?php echo $rowName?>_id" value="<?php echo $this->escapeHtmlAttr($translation['id'])?>" />
                                    <button type="submit" value="<?php echo $rowName?>" name="rowid" class="btn btn-primary btn-lg" data-toggle="tooltip" data-placement="left" title="Tooltip on left"><span class="glyphicon glyphicon-floppy-disk"></span></button>
                                    &nbsp;
                                    <button type="button" class="btn btn-default btn-lg"><span class="glyphicon glyphicon-pencil"></span></button>
                                </div>
                            <td>
                        </tr>
                    <?php endforeach; ?>

                </table>
                <input type="hidden" name="elements_in_form" value="<?php echo $rowNumber ?>" />
                <button type="submit" value="all" name="rowid" class="btn btn-primary">Save all</button>
            </form>
        </div>
    </div>

</div>
